"""add recovery cases table

Revision ID: 8e6f08c9455f
Revises: 3b2ac8f31136
Create Date: 2026-08-26 14:03:57.535500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6f08c9455f'
down_revision: Union[str, Sequence[str], None] = '3b2ac8f31136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('recovery_strategy', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_merchant_id'), 'recovery_cases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_priority'), 'recovery_cases', ['priority'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_transaction_id'), 'recovery_cases', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_transaction_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_priority'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_merchant_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    # ### end Alembic commands ###
