"""add recovery attempts table

Revision ID: a8fdaa7058ed
Revises: 8e6f08c9455f
Create Date: 2026-08-26 14:14:21.849753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fdaa7058ed'
down_revision: Union[str, Sequence[str], None] = '8e6f08c9455f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recovery_case_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_recovery_case_id'), 'recovery_attempts', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_status'), 'recovery_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_attempts_status'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_recovery_case_id'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    # ### end Alembic commands ###
