"""add recovery attempts table

Revision ID: ba8755e9d11b
Revises: a8fdaa7058ed
Create Date: 2026-08-26 19:41:36.853691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba8755e9d11b'
down_revision: Union[str, Sequence[str], None] = 'a8fdaa7058ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_attempts', sa.Column('channel', sa.String(length=32), nullable=False))
    op.add_column('recovery_attempts', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('recovery_attempts', sa.Column('provider_reference', sa.String(length=128), nullable=True))
    op.add_column('recovery_attempts', sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('recovery_attempts', 'attempt_number')
    op.drop_column('recovery_attempts', 'failure_reason')
    op.drop_column('recovery_attempts', 'executed_at')
    op.drop_column('recovery_attempts', 'amount_recovered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_attempts', sa.Column('amount_recovered', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('recovery_attempts', sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('recovery_attempts', sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recovery_attempts', sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('recovery_attempts', 'attempted_at')
    op.drop_column('recovery_attempts', 'provider_reference')
    op.drop_column('recovery_attempts', 'message')
    op.drop_column('recovery_attempts', 'channel')
    # ### end Alembic commands ###
