"""add merchant password hash

Revision ID: fbfbf5c05e01
Revises: 75be97f187de
Create Date: 2026-08-26 12:33:01.724498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfbf5c05e01'
down_revision: Union[str, Sequence[str], None] = '75be97f187de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'password_hash')
    # ### end Alembic commands ###
